server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  application:
    name: CoachBackend
    user-route: "api/v1/users/"
    auth-route: "api/v1/auth/"
  datasource:
    url: jdbc:postgresql://localhost:5432/coachdb
    username: amirgolmoradi
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # SECURITY CONFIG
  security:
    user:
      name: admin
      password: admin
    jwt:
      secret-key: 3d4d28498689bac821ec4b1718fe41ac93bc56e6540eaa76e09679184efc87d1
      expiration-time: 1_296_000_000 // 15 Days


    # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db/migration
  # Logging Configuration
logging:
  level:
    org.springframework.security: TRACE