server:
  port: 8181
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  application:
    name: CoachAI-Backend
    user-route: "api/v1/users/"
    auth-route: "api/v1/auth/"
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # SECURITY CONFIG
  security:
    user:
      name: admin
      password: admin
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 1_296_000_000 // 15 Days


    # Flyway Configuration
  flyway:
    baseline-on-migrate: true
    locations: db/migration
  # Logging Configuration
logging:
  level:
    org.springframework.security: trace